### ISSUE TITLE
[block-layout] We should have two columns of objects

### ISSUE THREAD

**Issue by jmacarthur** [CodethinkLabs/software-dependency-visualizer#14]
The original specification calls for two columns of objects which symbols inside them; we currently have one.

**Comment by palvarez89** [comment]
I've started looking at this. Do we want 2 columns in the same svg? In the specification we have something like one div per object (the object had an scrollbar so that not all the symbols were visible at the same time). If we want to move to that direction, drawing the call lines will be more complicated and this task should try to go in that direction/

Also we could just create 2 columns in in the svg, which will make drawing the lines easier, and it might be easier to visualise.

**Comment by jmacarthur** [comment]
I think it'd be easier to have both columns in one SVG as we can't easily make call lines that cross SVGs. I don't know whether we actually want scrollbars on individual objects; it's difficult to say whether that would make it easier to navigate.
